CREATE TABLE [dbo].[Employee]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Employee_Id] DEFAULT NEWSEQUENTIALID(),
    [Email] NVARCHAR(255) NOT NULL,
    [FirstName] NVARCHAR(100) NOT NULL,
    [LastName] NVARCHAR(100) NOT NULL,
    [Title] NVARCHAR(100) NOT NULL,
    [Office] INT NOT NULL,
    [PhoneNumber] NVARCHAR(50) NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([Id])
);